name: "Submit to Web Store"

on:
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ~/.pnpm-store
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "pnpm"

      - run: pnpm build
      - run: pnpm package

      - uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
